# Generated by Django 3.1.6 on 2021-02-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movieslist.Movie'),
        ),
    ]
