# Generated by Django 3.1.6 on 2021-02-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieslist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='list',
            new_name='movie_list',
        ),
    ]
